services:
  tg-dispatcher:
    container_name: tg-dispatcher
    hostname: tg-dispatcher
    image: tg-dispatcher
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "${VERSION}"
        GIT_COMMIT: "${COMMIT_HASH}"
        BUILD_TIME: "${BUILD_TIME}"
    environment:
      - CONFIG_PATH=/app/data/config.yaml,/app/data/config_auth.yaml
    volumes:
      - /project/internal/configs/tg-dispatcher/config.yaml:/app/data/config.yaml
      - /project/internal/configs/tg-dispatcher/config_auth.yaml:/app/data/config_auth.yaml
    networks:
      - tgqueue_default

networks:
  tgqueue_default:
    external: true
